### ISSUE TITLE
First-party sets demo https://first-party-sets.glitch.me/ does not work

### ISSUE THREAD

**Issue by vanvodk** [WICG/first-party-sets#167]
The demo site is mentioned in [this guideline](https://developer.chrome.com/en/docs/privacy-sandbox/first-party-sets-integration/#example) keeps saying `requestStorageAccess: Permission denied.` no matter what version of Chrome I try it on (Chrome Beta or Canary). Refer to the screenshot below
<img width="1596" alt="image" src="https://github.com/WICG/first-party-sets/assets/11583191/3c6b34d0-e5cb-470f-8298-3a09eb8a1db9">

1. So I am wondering if Exact required steps have been done, is there any unmentioned/implied steps I have to do to make it work? 
2. The developer guideline mentions mostly about top site and embedded site scenarios. I assume that site A and site B which are in the same set, where site A will set a cross-site cookie and site B will use the cookie for authentication to site A, will be able to retrieve each other's cookies, is that a correct statement?
3. Can I use `--use-first-party-set` to setup my current production sets to test locally?

**Comment by cfredric** [comment]
Hi @vanvodk,

> So I am wondering if Exact required steps have been done, is there any unmentioned/implied steps I have to do to make it work?

I just tried the demo steps in Chrome Stable (115.0.5790.110), Chrome Beta (116.0.5845.50), Chrome Dev (117.0.5897.3), and a local build of Chromium (117.0.5914.0), and it worked as I expected in all cases. Can you confirm that you started Chrome using the command-line flags listed in the [Example](https://developer.chrome.com/en/docs/privacy-sandbox/first-party-sets-integration/#example) section? Those flags are necessary for the demo to work properly.

>  I assume that site A and site B which are in the same set, where site A will set a cross-site cookie and site B will use the cookie for authentication to site A, will be able to retrieve each other's cookies, is that a correct statement?

No, that's not correct. Site A will only ever be able to access *its own* cookies; and site B will only ever be able to access *its own* cookies. First-Party Sets does not give any site the ability to access cookies belonging to a different site; this is an important security boundary that we designed First-Party Sets to uphold.

If, in your application, site A needs to get information that's stored in a cookie that belongs to site B, then site A will have to create a site B iframe, and coordinate with that iframe to have it read its own cookies then send the necessary information over to the site A document (e.g. via `postMessage`). In other words, site B has to cooperate in order for that data-sharing to be possible.

> Can I use --use-first-party-set to setup my current production sets to test locally?

Yes, please do! Our intention was for the `--use-first-party-set` flag to be a useful way of testing behavior locally, without having to submit a "real" First-Party Set on [the repository](https://github.com/GoogleChrome/first-party-sets) first.

**Comment by vanvodk** [comment]
Hi @cfredric 
The [guideline ](https://www.chromium.org/developers/how-tos/run-chromium-with-flags/) suggests using Windows shortcut does not work as there is a 256 characters limit. Here is my setup
 - Chrome Beta Version 116.0.5845.49

- My PowerShell command 
```
& "C:\Program Files\Google\Chrome Beta\Application\chrome.exe" --enable-features="FirstPartySets:FirstPartySetsClearSiteDataOnChangedSets/1,StorageAccessAPI,StorageAccessAPIForOriginExtension,PageInfoCookiesSubpage,PrivacySandboxFirstPartySetsUI" `
--use-first-party-set="{\"primary\": \"https://first-party-sets.glitch.me\", \"associatedSites\": [\"https://fps-member-1.glitch.me\"]}" `
https://first-party-sets.glitch.me/
```
- Another PowerShell command with an additional flag `--test-third-party-cookie-phaseout`
```
& "C:\Program Files\Google\Chrome Beta\Application\chrome.exe" --test-third-party-cookie-phaseout `
--enable-features="FirstPartySets,StorageAccessAPI,StorageAccessAPIForOriginExtension,PageInfoCookiesSubpage,PrivacySandboxFirstPartySetsUI" `
--use-first-party-set="{\"primary\": \"https://first-party-sets.glitch.me\", \"associatedSites\": [\"https://fps-member-1.glitch.me\"]}" `
https://first-party-sets.glitch.me/
```

**Comment by cfredric** [comment]
> The [guideline ](https://www.chromium.org/developers/how-tos/run-chromium-with-flags/)suggests using Windows shortcut does not work as there is a 256 characters limit.

I don't see that mentioned anywhere on the page you linked to. I don't have experience with PowerShell, but [Microsoft's documentation](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation) says that `cmd.exe` supports command lines of up to 8191 characters - could you try that instead of PowerShell? Or try the demo on a different platform?

Alternatively, you could try this:
1. Enable the First-Party Sets feature by enabling the `#enable-first-party-sets` flag on `chrome://flags`.
2. Quit Chrome by visiting `chrome://quit`.
3. Start Chrome with the following command line:
```
& "C:\Program Files\Google\Chrome BetaApplicationchrome.exe" --use-first-party-set="{"primary": "https://first-party-sets.glitch.me", "associatedSites": ["https://fps-member-1.glitch.me"]}" https://first-party-sets.glitch.me/
```
This is less than 256 chars (227 by my count), so it should work around that limit. It will not let you test the new UI treatment in Chrome (since it doesn't enable those Chrome features), but it should let you test the demo at least.

To do your own local testing, you can adjust the `--use-first-party-set=...` switch accordingly, and remove the final `https://first-party-sets.glitch.me/` argument if you need the space. (That final argument just tells Chrome which page to open when it starts up.)

**Comment by vanvodk** [comment]
Hi @cfredric 
I mean there is a limit in this shortcut's target attribute and I have no problem running the PowerShell mentioned previously.

<img width="268" alt="image" src="https://github.com/WICG/first-party-sets/assets/11583191/aaabf588-e0be-412c-842c-2a7646945483">

And I just did what you mentioned. I enabled these flags but seems like there is one flag which is not available in Chrome UI `StorageAccessAPIForOriginExtension`

<img width="561" alt="image" src="https://github.com/WICG/first-party-sets/assets/11583191/a13bd339-75c1-4639-85a0-f6abb77744ea">

In summary the same parameters passed into shortcut's target works while using PowerShell command does not. So I started to believe that there is something with the JSON format in command line case

Shortcut's Target value(redacted): 
```
"C:\...\Chrome SxS\Application\chrome.exe" --use-first-party-set="{\"primary\": \"https://first-party-sets.glitch.me\", \"associatedSites\": [\"https://fps-member-1.glitch.me\"]}" 
```
Powershell Command: 
```
& 'C:\Users\VanVD2\AppData\Local\Google\Chrome SxS\Application\chrome.exe' --use-first-party-set="{\"primary\": \"https://first-party-sets.glitch.me\", \"associatedSites\": [\"https://fps-member-1.glitch.me\"]}"
```

**Comment by cfredric** [comment]
> I enabled these flags but seems like there is one flag which is not available in Chrome UI `StorageAccessAPIForOriginExtension`

That's correct - there's no entry for that feature on chrome://flags, but it's still recognized when enabled in the `--enable-features="..."` switch on the command-line. Another way to enable the `StorageAccessAPIForOriginExtension` feature is by enabling the `#enable-experimental-web-platform-features` flag on `chrome://flags`, but please be aware that this flag enables a lot of experimental (and possibly unstable) features, so Chrome may not work as you expect.

----

Just FYI, the command-line and suggested instructions I gave in my previous comment were incorrect - those steps will only work if you also have the `#enable-experimental-web-platform-features` flag enabled. In order to make that command-line work without enabling that flag, we'd have to edit it to be this instead:

```
& "C:\Program Files\Google\Chrome Beta\Application\chrome.exe" --enable-features="StorageAccessAPIForOriginExtension" --use-first-party-set="{"primary": "https://first-party-sets.glitch.me", "associatedSites": ["https://fps-member-1.glitch.me"]}" https://first-party-sets.glitch.me/
```
Which is longer than 255 characters. But if there's no problem using PowerShell to run the command-line that we listed on [the testing instructions page](https://developer.chrome.com/en/docs/privacy-sandbox/first-party-sets-integration/#example), as you say, I highly recommend testing that way instead of using the shortcut.

----

By the way, please be aware that not all of the flags you've enabled on `chrome://flags` (according to the screenshot you attached) are related to this demo. Specifically:
* `#storage-access-api` is related; you can enable that flag instead of including `StorageAccessAPI` on the command-line.
* `#privacy-sandbox-ads-apis` is not related; the demo should work with or without that flag enabled.
* `#enable-first-party-sets` is related but not strictly necessary. Including `--use-first-party-set=...` on the command-line is sufficient to enable the underlying feature.
* `#third-party-storage-partitioning` is not related; the demo should work with or without that flag enabled.
* `#permission-storage-access-api` is not related; the demo should work with or without that flag enabled.

**Comment by cfredric** [comment]
@vanvodk I haven't heard from you in a few months, so I'm going to close this, assuming that you figured out the issue.
