### ISSUE TITLE
Clarifying question on blocking third party cookie requirement

### ISSUE THREAD

**Issue by ChristianEvc** [WICG/first-party-sets#173]
Hi, 

I have a clarifying question. In the "How to test locally" section there is a subsection for "Verify that third-party cookies are blocked". Is it the case that FPS will only work for users who have blocked all third party cookies? Or is this section only relevant for testing, and once FPRs is actually implemented by a publisher will work regardless of whether a specific user has blocked third party cookies or not?

Thanks!

**Comment by krgovind** [comment]
@ChristianEvc Thanks for the question. 

FPS/SAA will indeed work even when a user has not blocked third-party cookies; but it's just that there will be no observable effect in that scenario, since the relevant cookies are available without any need for FPS and Storage Access API (SAA). So yes, this is only relevant for testing.

**Comment by ChristianEvc** [comment]
Perfect, thanks very much @krgovind !!

**Comment by krgovind** [comment]
You're welcome! Thanks for testing the feature!
