### ISSUE TITLE
Help Understanding Associated Sites and Subdomains

### ISSUE THREAD

**Issue by bretticus-mc** [WICG/first-party-sets#185]
Let's say my RWS has an Associated Site/Service Domain for "https://example.com". Would "https://foo.example.com" be implicitly included in the Related Website Set?

**Comment by cfredric** [comment]
Related Website Sets are [defined](https://wicg.github.io/first-party-sets/#data-structures) in terms of [sites](https://web.dev/articles/same-site-same-origin#site), rather than [origins](https://web.dev/articles/same-site-same-origin#origin). So yes, `https://foo.example.com` and `https://example.com` are considered same-site, as long as the [Public Suffix List](https://publicsuffix.org/) doesn't include `example.com` or `foo.example.com` as entries.

**Comment by bretticus-mc** [comment]
Is this also the case for the RWS Set primaries as well?

**Comment by cfredric** [comment]
Yes, set primaries [are also sites](https://wicg.github.io/first-party-sets/#related-website-set-primary).

**Comment by krgovind** [comment]
Closing this assuming that @cfredric's response answers this question. Feel free to re-open otherwise.
