### ISSUE TITLE
Proposing changes to First-Party Sets based on community feedback

### ISSUE THREAD

**Issue by krgovind** [WICG/first-party-sets#92]
**Summary of proposed changes:**

Based on feedback received during the incubation of First-Party Sets in the Privacy Community Group, we are proposing changes to the proposal. Following is a high-level summary of the changes, on which we invite community feedback. Please review the linked sections below for additional detail.

All of these changes are part of PR #91 which we will review on an upcoming WICG call (see issue #89)

-   Define a set through [use-case-specific "subsets"](https://github.com/krgovind/first-party-sets#defining-a-set-through-use-case-based-subsets). Each subset category will have its own requirements, and browser handling approach.
-   [Leverage the Storage Access API](https://github.com/krgovind/first-party-sets#leveraging-the-storage-access-api) for sites to request cross-site cookie access, instead of the SameParty attribute.
-   Abandon development of the [SameParty cookie attribute](https://github.com/cfredric/sameparty), which allowed synchronous cookie access on subresource requests, and, for the most part, allowed legacy same-party flows to continue functioning with minimal adoption costs involved for web developers. However, it prevents browsers' ability to mediate these flows and potentially intervene on behalf of users.

**Benefits of proposed changes:**

-   Allows for more granular use-case specific requirements and browser handling policies that are more likely to align with user expectations.
-   Achieves alignment and interoperability with other browsers' approach to mediate cross-site cookie access via Storage Access API.

**Challenges:**

-   SAA involves greater adoption costs for web developers, compared to the SameParty cookie attribute. We hope to alleviate this to some extent via our [proposed extension to SAA](https://github.com/mreichhoff/requestStorageAccessForSite).

**Open question(s):**

-   We recognize that these changes also necessitate re-examining how [CHIPS](https://github.com/privacycg/CHIPS) [integrates with](https://developer.chrome.com/docs/privacy-sandbox/chips/#first-party-sets-and-cookie-partitioning) First-Party Sets. We are working on technical changes to that design as well, and will share updates when we have a proposal.

**Comment by dmarti** [comment]
Thank you, it is very encouraging to see sets that can be based on user understanding of a shared context that spans domains. This approach seems widely acceptable and relatively future-proof, aligned with the [W3C Privacy Principles draft definition of "party."](https://w3ctag.github.io/privacy-principles/#dfn-party)

Putting the set review process into a GitHub repository (or a similar collaboration tool) means that there will community management challenges for interactions between site owners proposing sets and independent reviewers evaluating set validity.  Discussions of valid/invalid sets are likely to become contentious and turn into moderation problems if they turn to matters of opinion about whether a set is "clearly presented to users."

In order to make GitHub (or similar) reviews of sets work as well as possible, it would be good to see what could be done to make the work of a public reviewer less open-ended and more rewarding. I added a suggestion that proposed sets should be accompanied by user research, on the real site audiences, that shows that the users do find that a set is "clearly presented." That way the public review process can start from a shared understanding of what the users are really understanding about a set.

**Comment by krgovind** [comment]
Closing this now since #91 has now been merged; and new issues have been opened to capture feedback and discussion.

**Comment by trishann7777** [comment]
Please let me say thank you Patricia Collier pcollier294@gmail.com

**Comment by samanmokhtarzadeh** [comment]
Good 💯

**Comment by samanmokhtarzadeh** [comment]
@samanmokhtarzadeh
